name: Test Alignment Viewer

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          - python-version: "3.6"
            os: ubuntu-20.04   # 👈 3.6 only works here
          - python-version: "3.x"
            os: ubuntu-latest  # 👈 keep latest for modern versions
    runs-on: ${{ matrix.os }}
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Install package
        run: pip install .
      - name: Run tests
        run: python -m pytest tests/ -v
